#!/usr/bin/env bash

account=$(aws sts get-caller-identity --query "Account" --output text)
bucket_name="twelve-factor-app-service-staging-$account"
package_name="twelve-factor-tomcat-$(uuidgen).zip"
stack_name="twelve-factor-tomcat-stack"
aws_region=$(aws configure get region)

# args (bucket-name, region)
function prepareBucket {
  echo "Creating staging bucket if necessary"
  if [ -z "$(aws s3api head-bucket --bucket "$1" 2>&1)" ]
  then
    echo "bucket exists, verifying region..."
    bucket_region=$(aws s3api get-bucket-location --bucket "$1" | jq .LocationConstraint | tr -d '"')
    if [ "$bucket_region" != "$2" ]
    then
      echo "Error: The staging bucket '$1' already exists in region $bucket_region"
      exit 1
    fi
  else
    echo "Info: The staging bucket does not yet exist and will be created in your configured region $aws_region"
    aws s3api create-bucket --bucket "$1" --region "$2" --create-bucket-configuration LocationConstraint="$2"
  fi
}

# main
echo "The stack will be deployed in region $aws_region"

# build the application binary
echo "Building binary"
./gradlew war

# package it
echo "Packaging binary and extensions"
rm -rf "$package_name"
zip -j "$package_name" build/libs/*.war

# stage it
prepareBucket "$bucket_name" "$aws_region"
echo "Staging to $bucket_name"
aws s3 cp "$package_name" "s3://$bucket_name"

echo "Building $stack_name..."
aws cloudformation deploy \
  --stack-name "$stack_name" \
  --template-file cloudformation/environment.yml \
  --capabilities CAPABILITY_IAM \
  --parameter-overrides \
      PackageName="$package_name" \
      BucketName="$bucket_name"
